import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const className = cn(`${nunito.className}`, "m-0 p-0");

  return (
    <html lang="en">
      <body className={className}>
        <Nav />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
